### ISSUE TITLE
package.json is missing

### ISSUE THREAD

**Issue by mickeyvip** [Kaizeras/ng2-redux-app#1]
this repo by itself is unusable since it is missing several config files, such as `package.json`

**Comment by Kaizeras** [comment]
[package.json is not missing](https://github.com/Kaizeras/ng2-redux-app/blob/master/package.json) . Are you using [angular-cli](https://github.com/angular/angular-cli) to build the project?

**Comment by mickeyvip** [comment]
Yes, I am using angular-cli and I have `package.json` generated automatically. I mean it is missing from this repo.

The reason I am pointing this out is because not all code snippets worked for me and I wanted to know what version of `@ngrx/store` were used in the article.

Specifically:

![image](https://cloud.githubusercontent.com/assets/220427/20556462/e391db50-b16f-11e6-94a9-af455506dcd4.png)
```
[default] /Users/michaelv/dev/IdeaProjects/financials-app/src/app/common/operations.ts:12:21
    Generic type 'State<T>' requires 1 type argument(s).
```

![image](https://cloud.githubusercontent.com/assets/220427/20556299/2e8b7360-b16f-11e6-94ae-a066aac8a9f1.png)
```
[default] /Users/me/financials-app/src/app/common/operations.ts:16:33
    Generic type 'ActionReducer<T>' requires 1 type argument(s).
[default] Checking finished with 2 errors
```

plus, inside `operationsReducer` there are multiple `const operation = ` inside `case` statements, producing:

```
[default] /Users/me/financials-app/src/app/common/operations.ts:25:19
    Cannot redeclare block-scoped variable 'operation'.
```

**Comment by mickeyvip** [comment]
Other than that - The article is very good, I have learned a lot. 

And it has the best visualization of Redux process I have ever seen!

Thank you!
